<?php
//echo $this->form;
?>
<div class="row">
    
    <div class="col-xs-12 col-md-8">
        <h1>Cadastrar Usuário</h1>
        </br>
        <form role="form">
            <div class="form-group">
                <label for="inputCodigo">Código</label>
                <input type="text" class="form-control" id="codigo" disabled="true">
            </div>
            <div class="form-group">
                <label for="inputNome">Nome</label>
                <input type="text" class="form-control" id="nome" placeholder="Nome">
            </div>
            <div class="form-group">
                <label for="inputEmail">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="inputSenha">Senha</label>
                <input type="password" class="form-control" id="senha" placeholder="Senha">
            </div>
            <div class="form-group">
                <label for="inputConfSenha">Confirmar Senha</label>
                <input type="password" class="form-control" id="senha" placeholder="Confirmar Senha">
            </div>
            <div class="form-group">
                <label for="inputPermissão">Permissão</label>
                <select type="text" class="form-control" id="permissao" placeholder="Selecione uma Permissão"></select>
            </div>

            <button type="submit" class="btn btn-default">Cadastrar</button>
        </form>
    </div>
    <div class="col-xs-6 col-md-4"></div>
</div>