<?php echo $this->doctype ?>   
<html>
    <head>
        <?php echo $this->headTitle("Aluga Casa Web") ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headMeta() ?>


        <?php $this->headLink()->appendStylesheet('http://getbootstrap.com/examples/sticky-footer-navbar/sticky-footer-navbar.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css', 'screen') ?>

        <?php echo $this->headLink() ?>
    </head>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Aluga Casa Web</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Inicio</a></li>
                    <li><a href="#about">Meus Imóveis</a></li>
                    <li><a href="#contact">Financeiro</a></li>
                    <li><a href="#contact">Mensagens</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'usuarios', 'action' => 'create'), null, true) ?>">Usuários</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Entrar <b class="caret"></b></a>
                        <form class="login-menu dropdown-menu well">
                            <fieldset>
                                <input type="email" class="form-control" placeholder="Email" required autofocus>
                                <input type="password" class="form-control" placeholder="Senha" required>
                                <label class="checkbox">
                                    <input type="checkbox" value="remember-me">Lembrar-me
                                </label>
                                <button class="btn btn-primary btn-sm btn-block" type="submit">Entrar</button>
                            </fieldset>
                        </form>



                    </li>
                </ul>
            </div>
        </div>
    </div>